### ISSUE TITLE
Unneeded Styles

### ISSUE THREAD

**Issue by jlag34** [oOFrancescaOo/prj-rev-bwfs-dasmoto#5]
https://github.com/oOFrancescaOo/prj-rev-bwfs-dasmoto/blob/88609abee654cdd055f2ef8e9dedda519aba63a0/DASMOTO/resources/css/style.css#L8-L12

You don't need to add this to your header elements. Header elements are already bold.

**Comment by oOFrancescaOo** [comment]
Oh, good to know.
Thank you!
