### ISSUE TITLE
Styling Headers

### ISSUE THREAD

**Issue by jlag34** [oOFrancescaOo/prj-rev-bwfs-dasmoto#7]
https://github.com/oOFrancescaOo/prj-rev-bwfs-dasmoto/blob/88609abee654cdd055f2ef8e9dedda519aba63a0/DASMOTO/resources/css/style.css#L17-L21

Great job styling your headers so that you don't have to repeat this code on a class.

**Comment by oOFrancescaOo** [comment]
Thx!
